name: 'Loop check 2'
on:
  workflow_dispatch: 



jobs:
  matrix_job_test:
    name: Matrix job test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@v4
        with: 
          package-name: ${{ env.STACK_NAME }}
          package-type: 'container'
          min-versions-to-keep: 3
          delete-only-pre-release-versions: "true"
          token: ${{ secrets.MY_TOKEN }}
        env:
          STACK_NAME: hello
