name: 'Loop check 2'
on:
  workflow_dispatch: 

jobs:
  test_job:
    name: Matrix job prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout-cone-mode: false
      - name: Get JSON content
        id: get-json-content
        run: |
          echo 'JSON_CONTENT<<EOF' >> $GITHUB_OUTPUT
          cat container-images.list.json >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
    outputs:
      new_content: ${{ steps.get-json-content.outputs.JSON_CONTENT }} 
  matrix_job_test:
    name: Matrix job test
    runs-on: ubuntu-latest
    needs: test_job
    strategy:
      matrix:
        include: ${{ fromJSON(needs.test_job.outputs.new_content) }}
    steps:
      - uses: actions/delete-package-versions@v4
        with: 
          package-name: '$STACK_NAME'
          package-type: 'npm'
          min-versions-to-keep: 10
          delete-only-pre-release-versions: "true"
        env:
          STACK_NAME: ${{ matrix.name }}      
