name: 'Loop check 2'
on:
  workflow_dispatch: 

jobs:

  setup:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.names.outputs.image_names }}
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout-cone-mode: false
      - name: Get Package Names
        id: names
        run: |
            names="[hello, babu]"
            echo "$names" 
            echo "image_names=$names" >> $GITHUB_OUTPUT
      - name: Get Package Names
        run: |
            echo "${{ steps.names.outputs.image_names }}"
  build:
    needs: [ setup ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{fromJSON(needs.setup.outputs.image_tag)}}
    steps:
      - run: |
          echo "${{ matrix.value }}"
