name: 'Loop check 2'
on:
  workflow_dispatch: 

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.names.outputs.image_names }}
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout-cone-mode: false
      - name: Get Package Names
        id: names
        run: |
          names="hello, babu"
          echo 'image_names=["'"${names}"'"]' >> "$GITHUB_OUTPUT"
      - name: Check Outputs
        run: |
            echo Value is "${{ steps.names.outputs.image_names }}"
  build:
    needs: [ setup ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ${{fromJson(needs.setup.outputs.image_tag)}}
    steps:
      - run: |
          echo "${{ matrix.os }}"
      
