name: 'Loop check 2'
on:
  workflow_dispatch: 

jobs:

  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
      - id: matrix
        run: |
          echo '::set-output name=value::["a", "b", "c"]'
  build:
    needs: [ setup ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{fromJSON(needs.setup.outputs.matrix)}}
    steps:
env:
          OUTPUT: ${{ steps.id.outputs.arr }}
      - run: |
          echo "${{ matrix.value }}"
