name: 'Loop check'
on:
  workflow_dispatch: 

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.names.outputs.image_names }}
    steps:
      - name: Get Package Names
        id: names
        run: |
            names=$(cat container-images.list.json | jq -r '.[] | .name' |  tr -s '\n' ',' | awk 'gsub(/,$/,x)')
            echo "$names" 
            echo "image_names=$names" >> $GITHUB_OUTPUT
  build:
    needs: prepare
    strategy:
      matrix:
        edition: ["${{ steps.names.outputs.image_names }}"]
    steps:
      - name: test
        run: |
          echo ${{ matrix.edition }}

