name: Delete old container images

on:
  workflow_dispatch:


jobs:
  clean-ghcr:
    name: Delete old unused container images
    runs-on: ubuntu-latest
    steps:

      - name: Delete all test containers older than a week, using a wildcard
        uses: snok/container-retention-policy@v2
        with:
          image-names: hello
          cut-off: A week ago UTC
          account-type: org
          org-name: bhsankbab
          keep-at-least: 1
          skip-tags: latest
          token: ${{ secrets.MY_TOKEN }}
          dry-run: true
