name: 'Container Delete'
on:
  workflow_dispatch: 

jobs:
  clean-ghcr:
    name: Delete old unused container images
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.names.outputs.image_names }}
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout-cone-mode: false
      - name: Get Package Names
        id: names
        run: |
            names=$(cat container-list.txt |  tr -s '\n' ',' | awk 'gsub(/,$/,x)')
            echo "$names" 
            echo "image_names=$names" >> $GITHUB_OUTPUT
      - name: Check outputs
        run: |
          echo " Value from Output displays here "
          echo ${{ steps.names.outputs.image_names }}
      - name: Delete all test containers older than six months, using a wildcard
        uses: snok/container-retention-policy@v2
        with:
          image-names: '${{ steps.names.outputs.image_names }}'
          cut-off: A week ago UTC
          account-type: org
          org-name: bhsankbab
          keep-at-least: 1
          skip-tags: latest
          token: ${{ secrets.MY_TOKEN }}
          dry-run: true
