name: 'Container Delete'
on:
  workflow_dispatch: 
env:
  org: bhsankbab
jobs:
  clean-ghcr:
    name: Delete old unused container images
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.names.outputs.image_names }}
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout-cone-mode: false
      - name: Get Package Names
        id: names
        run: |
            for ((i=0;i<=40;i++)); do
            echo $i;
            curl -s  -L   -H "Accept: application/vnd.github+json"   -H "Authorization: Bearer ${{ secrets.MY_TOKEN }}"  -H "X-GitHub-Api-Version: 2022-11-28"   "https://api.github.com/orgs/${{ env.org }}/packages?package_type=container&per_page=100&page=$i" | jq -r ' .[] |  .name ' | sed 's/null//' |sed '/^[[:space:]]*$/d' | sort >> pages.txt
            cat pages.txt | sort > sorted_page.txt
            cat sorted_page.txt |  tr -s '\n' ',' | awk 'gsub(/,$/,x)' > comma-separated
            done
            cat pages.txt
            cat sorted_page.txt
            cat comma-separated
            names=$(cat comma-separated)
            echo "$names" 
            echo "image_names=$names" >> $GITHUB_OUTPUT
      - name: Check outputs
        run: |
          echo " Value from Output displays here "
          echo ${{ steps.names.outputs.image_names }}
      - name: Delete all test containers older than two days, using a wildcard
        uses: snok/container-retention-policy@v2
        with:
          image-names: '${{ steps.names.outputs.image_names }}'
          cut-off: two days ago UTC
          account-type: org
          org-name: bhsankbab
          keep-at-least: 1
          skip-tags: latest
          token: ${{ secrets.MY_TOKEN }}
          dry-run: true
