name: 'NPM Package Delete'
on:
  workflow_dispatch: 

jobs:
  clean-ghcr:
    name: Delete old unused NPM Packages
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.names.outputs.image_names }}
    steps:
      - uses: actions/delete-package-versions@v4
        with: 
          package-name: 'test-package'
          package-type: 'npm'
          min-versions-to-keep: 10
          delete-only-pre-release-versions: "true"
